### ISSUE TITLE
Ignores command parameter

### ISSUE THREAD

**Issue by luckydonald** [AlexMl/SyncChest#7]
The server log confirms I typed the command, but I'll get the help output instead.
![image](https://cloud.githubusercontent.com/assets/2737108/12078369/19a7691e-b20f-11e5-8d9c-51545afe2e4e.png)

**Comment by luckydonald** [comment]
Found an exception when starting the server:
```java
[11:48:01 ERROR]: Error occurred while enabling SyncChest v1.2.3 (Is it up to date?)
java.lang.NullPointerException
        at org.util.tools.ChestFileConverter.worldsInNames(ChestFileConverter.java:50) ~[?:?]
        at me.Aubli.SyncChest.SyncChest.onEnable(SyncChest.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by luckydonald** [comment]
So [ChestFileConverter.java:50](https://github.com/AlexMl/SyncChest/blob/5812b55ac71b1d12ea265ca1918760bf178c510a/src/org/util/tools/ChestFileConverter.java#L50) 
```java
for(File f : mainChestFolder.listFiles())
```
 is looking some settings folder it didn't create on my system.
I initially loaded the plugin with the `reload` server command.

**Comment by luckydonald** [comment]
[Bukket Documentation for `getDataFolder`](https://jd.bukkit.org/org/bukkit/plugin/java/JavaPlugin.html#getDataFolder()) states:
> Returns the folder that the plugin data's files are located in. The folder may not yet exist.

This seems to be the case that the folder isn't created.

**Comment by luckydonald** [comment]
Also please use `File.seperator` or something like that instead of using `/`. Not all file systems work the same. Windows uses `\`.
